from __future__ import annotations

from pathlib import Path

from PySide6.QtCore import Qt
from PySide6.QtWidgets import (
    QCheckBox,
    QComboBox,
    QFormLayout,
    QGroupBox,
    QHBoxLayout,
    QLabel,
    QLineEdit,
    QPushButton,
    QScrollArea,
    QSpinBox,
    QSplitter,
    QTextEdit,
    QVBoxLayout,
    QWidget,
)


def build_config_tab(window) -> None:
    outer_layout = QVBoxLayout(window.config_tab)
    outer_layout.setContentsMargins(10, 10, 10, 10)
    outer_layout.setSpacing(0)

    scroll_area = QScrollArea()
    scroll_area.setWidgetResizable(True)
    scroll_area.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)

    content = QWidget()
    root_layout = QVBoxLayout(content)
    root_layout.setContentsMargins(8, 8, 8, 8)
    root_layout.setSpacing(12)

    hero_group = QGroupBox("配置中心")
    hero_layout = QVBoxLayout(hero_group)
    hero_layout.setSpacing(8)
    hero_title = QLabel("Configuration Workspace")
    hero_title.setProperty("role", "heroTitle")
    hero_subtitle = QLabel("仅负责浏览器、代理、风控和 OAuth2 参数配置，不承载执行控制与日志结果。")
    hero_subtitle.setProperty("role", "heroSubtitle")
    hero_layout.addWidget(hero_title)
    hero_layout.addWidget(hero_subtitle)

    helper_group = QGroupBox("配置操作")
    helper_layout = QHBoxLayout(helper_group)
    helper_layout.setSpacing(10)
    window.save_button = QPushButton("保存配置")
    window.reload_button = QPushButton("重新加载")
    helper_hint = QLabel("配置页只维护高级参数；注册任务数、并发数和邮箱后缀请在注册页调整，保存后直接回到注册页启动。")
    helper_hint.setProperty("role", "sectionHint")
    helper_hint.setWordWrap(True)
    helper_layout.addWidget(window.save_button)
    helper_layout.addWidget(window.reload_button)
    helper_layout.addWidget(helper_hint, 1)

    content_splitter = QSplitter(Qt.Horizontal)

    left_panel = QWidget()
    left_layout = QVBoxLayout(left_panel)
    left_layout.setContentsMargins(0, 0, 0, 0)
    left_layout.setSpacing(12)

    right_panel = QWidget()
    right_layout = QVBoxLayout(right_panel)
    right_layout.setContentsMargins(0, 0, 0, 0)
    right_layout.setSpacing(12)

    config_group = QGroupBox("基础配置")
    config_form = QFormLayout(config_group)
    config_form.setSpacing(10)
    config_form.setLabelAlignment(Qt.AlignLeft)
    config_form.setFormAlignment(Qt.AlignTop)

    browser_group = QGroupBox("浏览器配置")
    browser_form = QFormLayout(browser_group)
    browser_form.setSpacing(10)
    browser_form.setLabelAlignment(Qt.AlignLeft)
    browser_form.setFormAlignment(Qt.AlignTop)

    proxy_group = QGroupBox("代理与网络")
    proxy_form = QFormLayout(proxy_group)
    proxy_form.setSpacing(10)
    proxy_form.setLabelAlignment(Qt.AlignLeft)
    proxy_form.setFormAlignment(Qt.AlignTop)

    window.browser_combo = QComboBox()
    window.browser_combo.addItems(["patchright", "playwright"])
    window.email_domain_combo = QComboBox()
    window.email_domain_combo.addItems(["hotmail.com", "outlook.com"])
    window.proxy_input = QLineEdit()
    window.route_intercept_enabled = QCheckBox("启用路由拦截(节省代理流量)")
    window.headless_enabled = QCheckBox("启用无头浏览器")
    window.bot_wait_input = QSpinBox()
    window.bot_wait_input.setRange(0, 999)
    window.captcha_retry_input = QSpinBox()
    window.captcha_retry_input.setRange(0, 20)
    window.max_browsers_input = QSpinBox()
    window.max_browsers_input.setRange(1, 100)
    window.playwright_path_input = QLineEdit()
    window.ezcaptcha_input = QLineEdit()
    window.sms_activate_input = QLineEdit()
    window.max_risk_input = QSpinBox()
    window.max_risk_input.setRange(1, 50)
    window.max_failure_streak_input = QSpinBox()
    window.max_failure_streak_input.setRange(1, 100)
    window.max_task_duration_input = QSpinBox()
    window.max_task_duration_input.setRange(10, 3600)
    window.max_sms_wait_cycles_input = QSpinBox()
    window.max_sms_wait_cycles_input.setRange(1, 120)

    browser_form.addRow("浏览器类型", window.browser_combo)
    browser_form.addRow(window.headless_enabled)
    browser_form.addRow("Playwright 浏览器路径", window.playwright_path_input)
    browser_form.addRow("浏览器池大小", window.max_browsers_input)

    proxy_form.addRow("静态代理地址", window.proxy_input)

    config_form.addRow("机器人等待时间(秒)", window.bot_wait_input)
    config_form.addRow("验证码重试次数", window.captcha_retry_input)
    config_form.addRow("EzCaptcha Key", window.ezcaptcha_input)
    config_form.addRow("SmsActivate Key", window.sms_activate_input)
    config_form.addRow("连续风险熔断阈值", window.max_risk_input)
    config_form.addRow("连续失败熔断阈值", window.max_failure_streak_input)
    config_form.addRow("单任务最大时长(秒)", window.max_task_duration_input)
    config_form.addRow("短信轮询次数上限", window.max_sms_wait_cycles_input)

    oauth_group = QGroupBox("OAuth2 配置")
    oauth_form = QFormLayout(oauth_group)
    oauth_form.setSpacing(10)
    oauth_form.setLabelAlignment(Qt.AlignLeft)
    oauth_form.setFormAlignment(Qt.AlignTop)
    window.oauth_enabled = QCheckBox("启用 OAuth2")
    window.client_id_input = QLineEdit()
    window.client_id_input.setEchoMode(QLineEdit.Password)
    window.client_id_input.setPlaceholderText("OAuth Client ID")
    window.client_id_visible_toggle = QCheckBox("显示 Client ID")
    window.redirect_url_input = QLineEdit()
    window.oauth_retry_attempts_input = QSpinBox()
    window.oauth_retry_attempts_input.setRange(1, 20)
    window.oauth_retry_interval_input = QSpinBox()
    window.oauth_retry_interval_input.setRange(0, 300)
    window.oauth_initial_wait_seconds_input = QSpinBox()
    window.oauth_initial_wait_seconds_input.setRange(0, 60)
    window.oauth_callback_timeout_handled_seconds_input = QSpinBox()
    window.oauth_callback_timeout_handled_seconds_input.setRange(1, 120)
    window.oauth_callback_timeout_unhandled_seconds_input = QSpinBox()
    window.oauth_callback_timeout_unhandled_seconds_input.setRange(1, 120)
    window.oauth_callback_timeout_retry_handled_seconds_input = QSpinBox()
    window.oauth_callback_timeout_retry_handled_seconds_input.setRange(1, 120)
    window.oauth_callback_timeout_retry_unhandled_seconds_input = QSpinBox()
    window.oauth_callback_timeout_retry_unhandled_seconds_input.setRange(1, 120)
    window.scopes_input = QTextEdit()
    window.scopes_input.setPlaceholderText("每行一个 Scope")
    window.scopes_input.setFixedHeight(180)
    oauth_form.addRow(window.oauth_enabled)
    oauth_form.addRow("Client ID", window.client_id_input)
    oauth_form.addRow("显示设置", window.client_id_visible_toggle)
    oauth_form.addRow("Redirect URL", window.redirect_url_input)
    oauth_form.addRow("OAuth 重试次数", window.oauth_retry_attempts_input)
    oauth_form.addRow("OAuth 重试间隔(秒)", window.oauth_retry_interval_input)
    oauth_form.addRow("OAuth 初始等待(秒)", window.oauth_initial_wait_seconds_input)
    oauth_form.addRow("首次回调等待-已处理(秒)", window.oauth_callback_timeout_handled_seconds_input)
    oauth_form.addRow("首次回调等待-未处理(秒)", window.oauth_callback_timeout_unhandled_seconds_input)
    oauth_form.addRow("二次回调等待-已处理(秒)", window.oauth_callback_timeout_retry_handled_seconds_input)
    oauth_form.addRow("二次回调等待-未处理(秒)", window.oauth_callback_timeout_retry_unhandled_seconds_input)
    oauth_form.addRow("Scopes", window.scopes_input)

    dynamic_proxy_group = QGroupBox("动态住宅代理与流量优化")
    dynamic_proxy_form = QFormLayout(dynamic_proxy_group)
    dynamic_proxy_form.setSpacing(10)
    dynamic_proxy_form.setLabelAlignment(Qt.AlignLeft)
    dynamic_proxy_form.setFormAlignment(Qt.AlignTop)
    window.dynamic_proxy_enabled = QCheckBox("启用动态住宅代理")
    window.dynamic_proxy_provider_input = QLineEdit()
    window.dynamic_proxy_provider_input.setPlaceholderText("例如：Kookeey")
    window.dynamic_proxy_mode_input = QComboBox()
    window.dynamic_proxy_mode_input.addItems(["api", "direct"])
    window.dynamic_proxy_api_url_input = QLineEdit()
    window.dynamic_proxy_api_url_input.setPlaceholderText("模式一：填写 Kookeey pickdynamicips 提取链接")
    window.dynamic_proxy_endpoint_input = QLineEdit()
    window.dynamic_proxy_endpoint_input.setPlaceholderText("模式二：填写独享端口或 username:password@host:port")
    window.dynamic_proxy_username_input = QLineEdit()
    window.dynamic_proxy_username_input.setPlaceholderText("仅 direct 模式使用；一体化代理串可留空")
    window.dynamic_proxy_password_input = QLineEdit()
    window.dynamic_proxy_password_input.setEchoMode(QLineEdit.Password)
    window.dynamic_proxy_password_input.setPlaceholderText("仅 direct 模式使用；一体化代理串可留空")
    window.dynamic_proxy_country_input = QLineEdit()
    window.dynamic_proxy_country_input.setPlaceholderText("可选，例如：US")
    window.dynamic_proxy_session_input = QLineEdit()
    window.dynamic_proxy_session_input.setPlaceholderText("可选，会话标识")
    window.dynamic_proxy_sticky_minutes_input = QSpinBox()
    window.dynamic_proxy_sticky_minutes_input.setRange(1, 10080)
    window.dynamic_proxy_sticky_minutes_input.setValue(30)
    dynamic_proxy_form.addRow(window.dynamic_proxy_enabled)
    dynamic_proxy_form.addRow("代理服务商", window.dynamic_proxy_provider_input)
    dynamic_proxy_form.addRow("代理模式", window.dynamic_proxy_mode_input)
    dynamic_proxy_form.addRow("API 提取链接", window.dynamic_proxy_api_url_input)
    dynamic_proxy_form.addRow("直连代理入口", window.dynamic_proxy_endpoint_input)
    dynamic_proxy_form.addRow("直连代理用户名", window.dynamic_proxy_username_input)
    dynamic_proxy_form.addRow("直连代理密码", window.dynamic_proxy_password_input)
    dynamic_proxy_form.addRow("国家代码", window.dynamic_proxy_country_input)
    dynamic_proxy_form.addRow("会话标识", window.dynamic_proxy_session_input)
    dynamic_proxy_form.addRow("粘性时长(分钟)", window.dynamic_proxy_sticky_minutes_input)
    dynamic_proxy_form.addRow(window.route_intercept_enabled)
    dynamic_proxy_hint = QLabel("推荐使用 Kookeey 模式一（api）：直接填写 pickdynamicips 提取链接，程序会在每次取代理时自动拉取可用入口。只有在需要固定独享端口时，再切换到 direct 模式并填写直连代理入口/用户名/密码。动态住宅代理与路由拦截都属于代理流量策略，建议在这里统一配置。路由拦截当前仅阻止 image / media / font。")
    dynamic_proxy_hint.setWordWrap(True)
    dynamic_proxy_hint.setProperty("role", "sectionHint")
    dynamic_proxy_form.addRow(dynamic_proxy_hint)

    mam_group = QGroupBox("microsoft-account-manager 上传配置")
    mam_form = QFormLayout(mam_group)
    mam_form.setSpacing(10)
    mam_form.setLabelAlignment(Qt.AlignLeft)
    mam_form.setFormAlignment(Qt.AlignTop)
    window.mam_enabled_checkbox = QCheckBox("启用上传")
    window.mam_base_url_input = QLineEdit()
    window.mam_base_url_input.setPlaceholderText("例如：https://your-worker.example.com")
    window.mam_ingest_path_input = QLineEdit()
    window.mam_ingest_path_input.setPlaceholderText("默认：/api/upload/ingest")
    window.mam_ingest_token_input = QLineEdit()
    window.mam_ingest_token_input.setEchoMode(QLineEdit.Password)
    window.mam_ingest_token_input.setPlaceholderText("x-ingest-token")
    window.mam_upload_after_oauth_checkbox = QCheckBox("OAuth2 成功后自动上传")
    window.mam_remark_input = QLineEdit()
    window.mam_remark_input.setPlaceholderText("写入 microsoft-account-manager 的备注")
    mam_form.addRow(window.mam_enabled_checkbox)
    mam_form.addRow("Base URL", window.mam_base_url_input)
    mam_form.addRow("Ingest Path", window.mam_ingest_path_input)
    mam_form.addRow("Ingest Token", window.mam_ingest_token_input)
    mam_form.addRow(window.mam_upload_after_oauth_checkbox)
    mam_form.addRow("Remark", window.mam_remark_input)

    left_layout.addWidget(browser_group)
    left_layout.addWidget(proxy_group)
    left_layout.addWidget(config_group)
    left_layout.addWidget(dynamic_proxy_group)
    left_layout.addStretch(1)

    right_layout.addWidget(oauth_group)
    right_layout.addWidget(mam_group)
    right_layout.addStretch(1)

    content_splitter.addWidget(left_panel)
    content_splitter.addWidget(right_panel)
    content_splitter.setSizes([900, 520])

    root_layout.addWidget(hero_group)
    root_layout.addWidget(helper_group)
    root_layout.addWidget(content_splitter)

    scroll_area.setWidget(content)
    outer_layout.addWidget(scroll_area)

    window.save_button.clicked.connect(window._save_form_to_config)
    window.reload_button.clicked.connect(window._load_config_to_form)
    window.client_id_visible_toggle.toggled.connect(
        lambda checked: window.client_id_input.setEchoMode(QLineEdit.Normal if checked else QLineEdit.Password)
    )
    window.dynamic_proxy_mode_input.currentTextChanged.connect(window._sync_dynamic_proxy_mode_ui)
    window._sync_dynamic_proxy_mode_ui(window.dynamic_proxy_mode_input.currentText())



def sync_dynamic_proxy_mode_ui(window, mode: str) -> None:
    normalized_mode = str(mode or "api").strip().lower()
    is_api = normalized_mode == "api"
    window.dynamic_proxy_api_url_input.setEnabled(is_api)
    window.dynamic_proxy_endpoint_input.setEnabled(not is_api)
    window.dynamic_proxy_username_input.setEnabled(not is_api)
    window.dynamic_proxy_password_input.setEnabled(not is_api)
